name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [master]
    types: [completed]

jobs:
  netlify-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workdir: "./rizome"
            siteId: BLOG_NETLIFY_ID
            projectName: rizome.io blog

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn --version
      - run: yarn install
      - run: yarn build
        working-directory: ${{ matrix.workdir }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          deploy-message: Automated CD deploy
          publish-dir: ${{ matrix.workdir }}/public
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: ${{ matrix.projectName }} Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[matrix.siteId] }}
        timeout-minutes: 1
